# Generated by Django 5.0.6 on 2024-07-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fecha_de_creacion',
            new_name='created',
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
