# Generated by Django 5.0.6 on 2024-07-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcstore', '0002_rename_fecha_de_creacion_product_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
