# Generated by Django 5.0.6 on 2024-07-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcstore', '0003_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
